In [1]:
# Install OS dependencies.  This only needs to be run once for each new notebook instance.
!pip install PyAthena

You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
!pip install pydotplus

You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame
from sklearn import neighbors
import seaborn as sns
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve, auc
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.metrics import *
from sklearn.model_selection import KFold
from numpy import mean, array
from sklearn.model_selection import ShuffleSplit
from sklearn.svm import SVC
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn import svm
import matplotlib
matplotlib.use('Agg')

/home/ec2-user/anaconda3/envs/python2/lib/python2.7/site-packages/ipykernel/__main__.py:39: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/home/ec2-user/anaconda3/envs/python2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ec2-user/anaconda3/envs/python2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ec2-user/anaconda3/envs/python2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ec2-user/anaconda3/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home

In [4]:
def printResults(Y_test, predictions):
    #print("\nTraining error: " + str(training_error))
    print("Accuracy: "+str(accuracy_score(Y_test, predictions)))
    print(confusion_matrix(Y_test, predictions))
    print(classification_report(Y_test, predictions))
    #print("False -ve = " + str(confusion_matrix(Y_test, predictions)[1][0] / (confusion_matrix(Y_test, predictions)[1][0]+confusion_matrix(Y_test, predictions)[0][0])))

In [5]:
X6_train=pd.read_csv('./Data/X6_train.csv',index_col=False)
Y6_train=pd.read_csv('./Data/Y6_train.csv').iloc[:,-1]

X12_train=pd.read_csv('./Data/X12_train.csv',index_col=False)
Y12_train=pd.read_csv('./Data/Y12_train.csv').iloc[:,-1]

X18_train=pd.read_csv('./Data/X18_train.csv',index_col=False)
Y18_train=pd.read_csv('./Data/Y18_train.csv').iloc[:,-1]

In [6]:
X6_test=pd.read_csv('./Data/X6_test.csv', index_col=False)
Y6_test=pd.read_csv('./Data/Y6_test.csv').iloc[:,-1]

X12_test=pd.read_csv('./Data/X12_test.csv', index_col=False)
Y12_test=pd.read_csv('./Data/Y12_test.csv').iloc[:,-1]

X18_test=pd.read_csv('./Data/X18_test.csv', index_col=False)
Y18_test=pd.read_csv('./Data/Y18_test.csv').iloc[:,-1]

In [7]:
matplotlib.rcParams.update({'font.size': 15})

In [8]:
def logistic_regression_pred(X_train, Y_train, X_test):
    log_reg_clsf_c = LogisticRegression(C = 10, penalty='l2').fit(X_train,Y_train)
    predictions = log_reg_clsf_c.predict(X_test)
    training_error = log_reg_clsf_c.score(X_train,Y_train)
    return predictions

In [9]:
def random_forest_pred(X_train, Y_train, X_test):
    rnd_frst_clsf_c = RandomForestClassifier(n_estimators = 100, max_depth=6, n_jobs=4, oob_score=True).fit(X_train, Y_train)
    predictions = rnd_frst_clsf_c.predict(X_test)
    return predictions

In [10]:
def neural_ntwrk_pred(X_train, Y_train, X_test):
    neural_ntwrk_clsf_c = MLPClassifier(activation='relu', hidden_layer_sizes=(9, 7)).fit(X_train,Y_train)
    predictions = neural_ntwrk_clsf_c.predict(X_test)
    return predictions

In [11]:
def svm_pred(X_train, Y_train, X_test):
    #TODO:train a SVM classifier using X_train and Y_train. Use this to predict labels of X_test
    svm_clasf_c = LinearSVC().fit(X_train,Y_train)
    predictions = svm_clasf_c.predict(X_test)
    return predictions

In [12]:
def decisionTree_pred(X_train, Y_train, X_test):
    desc_tree_clasf_c = DecisionTreeClassifier(max_depth=5).fit(X_train,Y_train)
    predictions = desc_tree_clasf_c.predict(X_test)
    return predictions

In [13]:
def classification_metrics(Y_pred, Y_true ):
    accuracy_c = accuracy_score(Y_pred,Y_true)
    auc_c = roc_auc_score(Y_pred,Y_true)
    precision_c = precision_score(Y_pred,Y_true)
    recall_c = recall_score(Y_pred,Y_true)
    f_Score_c = f1_score(Y_pred,Y_true)
    return accuracy_c,auc_c,precision_c,recall_c,f_Score_c

In [14]:
def display_metrics(classifierName,Y_pred,Y_true):
    print("______________________________________________")
    print(("Classifier: "+classifierName))
    acc, auc_, precision, recall, f1score = classification_metrics(Y_pred,Y_true)
    print(("Accuracy: "+str(acc)))
    print(("AUC: "+str(auc_)))
    print(("Precision: "+str(precision)))
    print(("Recall: "+str(recall)))
    print(("F1-score: "+str(f1score)))
    #print("Training error: " + str(training_error))
    print("______________________________________________")
    print("")
    printResults(Y_true, Y_pred)


In [15]:
    display_metrics("Logistic Regression",logistic_regression_pred(X6_train,Y6_train,X6_test),Y6_test)

/home/ec2-user/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


______________________________________________
Classifier: Logistic Regression
Accuracy: 0.9477533960292581
AUC: 0.9530956848030019
Precision: 1.0
Recall: 0.9061913696060038
F1-score: 0.9507874015748031
______________________________________________

Accuracy: 0.9477533960292581
[[848 100]
 [  0 966]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94       948
           1       0.91      1.00      0.95       966

   micro avg       0.95      0.95      0.95      1914
   macro avg       0.95      0.95      0.95      1914
weighted avg       0.95      0.95      0.95      1914



In [16]:
  display_metrics("Logistic Regression",logistic_regression_pred(X12_train,Y12_train,X12_test),Y12_test)

______________________________________________
Classifier: Logistic Regression
Accuracy: 0.9532054281703323
AUC: 0.956633692173407
Precision: 0.9990539262062441
Recall: 0.9142857142857143
F1-score: 0.9547920433996384
______________________________________________

Accuracy: 0.9532054281703323
[[ 981   99]
 [   1 1056]]
              precision    recall  f1-score   support

           0       1.00      0.91      0.95      1080
           1       0.91      1.00      0.95      1057

   micro avg       0.95      0.95      0.95      2137
   macro avg       0.96      0.95      0.95      2137
weighted avg       0.96      0.95      0.95      2137



In [17]:
  display_metrics("Logistic Regression",logistic_regression_pred(X18_train,Y18_train,X18_test),Y18_test)

______________________________________________
Classifier: Logistic Regression
Accuracy: 0.9492455418381345
AUC: 0.9550819362286859
Precision: 0.9991150442477876
Recall: 0.9112187247780468
F1-score: 0.953144786829886
______________________________________________

Accuracy: 0.9492455418381345
[[ 947  110]
 [   1 1129]]
              precision    recall  f1-score   support

           0       1.00      0.90      0.94      1057
           1       0.91      1.00      0.95      1130

   micro avg       0.95      0.95      0.95      2187
   macro avg       0.96      0.95      0.95      2187
weighted avg       0.95      0.95      0.95      2187



In [18]:
    display_metrics("Decision Tree",decisionTree_pred(X6_train,Y6_train,X6_test),Y6_test)

______________________________________________
Classifier: Decision Tree
Accuracy: 0.9644723092998955
AUC: 0.9646665734290184
Precision: 0.9730848861283644
Recall: 0.9572301425661914
F1-score: 0.9650924024640657
______________________________________________

Accuracy: 0.9644723092998955
[[906  42]
 [ 26 940]]
              precision    recall  f1-score   support

           0       0.97      0.96      0.96       948
           1       0.96      0.97      0.97       966

   micro avg       0.96      0.96      0.96      1914
   macro avg       0.96      0.96      0.96      1914
weighted avg       0.96      0.96      0.96      1914



In [19]:
    display_metrics("Decision Tree",decisionTree_pred(X12_train,Y12_train,X12_test),Y12_test)

______________________________________________
Classifier: Decision Tree
Accuracy: 0.9681796911558259
AUC: 0.9682521329339009
Precision: 0.9772942289498581
Recall: 0.9591457753017641
F1-score: 0.9681349578256794
______________________________________________

Accuracy: 0.9681796911558259
[[1036   44]
 [  24 1033]]
              precision    recall  f1-score   support

           0       0.98      0.96      0.97      1080
           1       0.96      0.98      0.97      1057

   micro avg       0.97      0.97      0.97      2137
   macro avg       0.97      0.97      0.97      2137
weighted avg       0.97      0.97      0.97      2137



In [20]:
    display_metrics("Decision Tree",decisionTree_pred(X18_train,Y18_train,X18_test),Y18_test)

______________________________________________
Classifier: Decision Tree
Accuracy: 0.9638774577046182
AUC: 0.9653162512512934
Precision: 0.9858407079646018
Recall: 0.9464740866610025
F1-score: 0.9657563935847421
______________________________________________

Accuracy: 0.9638774577046182
[[ 994   63]
 [  16 1114]]
              precision    recall  f1-score   support

           0       0.98      0.94      0.96      1057
           1       0.95      0.99      0.97      1130

   micro avg       0.96      0.96      0.96      2187
   macro avg       0.97      0.96      0.96      2187
weighted avg       0.96      0.96      0.96      2187



In [21]:
    display_metrics("SVM",svm_pred(X6_train,Y6_train,X6_test),Y6_test)

______________________________________________
Classifier: SVM
Accuracy: 0.9456635318704284
AUC: 0.9511880096687653
Precision: 0.9989648033126294
Recall: 0.903558052434457
F1-score: 0.9488692232055064
______________________________________________

Accuracy: 0.9456635318704284
[[845 103]
 [  1 965]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94       948
           1       0.90      1.00      0.95       966

   micro avg       0.95      0.95      0.95      1914
   macro avg       0.95      0.95      0.95      1914
weighted avg       0.95      0.95      0.95      1914



In [22]:
    display_metrics("SVM",svm_pred(X12_train,Y12_train,X12_test),Y12_test)

______________________________________________
Classifier: SVM
Accuracy: 0.9518015910154423
AUC: 0.9554478239929716
Precision: 0.9990539262062441
Recall: 0.9119170984455959
F1-score: 0.9534988713318284
______________________________________________

Accuracy: 0.9518015910154423
[[ 978  102]
 [   1 1056]]
              precision    recall  f1-score   support

           0       1.00      0.91      0.95      1080
           1       0.91      1.00      0.95      1057

   micro avg       0.95      0.95      0.95      2137
   macro avg       0.96      0.95      0.95      2137
weighted avg       0.96      0.95      0.95      2137



In [23]:
    display_metrics("SVM",svm_pred(X18_train,Y18_train,X18_test),Y18_test)

______________________________________________
Classifier: SVM
Accuracy: 0.9492455418381345
AUC: 0.9552780016116036
Precision: 1.0
Recall: 0.9105560032232071
F1-score: 0.9531843104175453
______________________________________________

Accuracy: 0.9492455418381345
[[ 946  111]
 [   0 1130]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94      1057
           1       0.91      1.00      0.95      1130

   micro avg       0.95      0.95      0.95      2187
   macro avg       0.96      0.95      0.95      2187
weighted avg       0.95      0.95      0.95      2187



In [24]:
    display_metrics("Random  Forest",random_forest_pred(X6_train,Y6_train,X6_test),Y6_test)

______________________________________________
Classifier: Random  Forest
Accuracy: 0.9686520376175548
AUC: 0.9698326469815123
Precision: 0.9917184265010351
Recall: 0.9485148514851485
F1-score: 0.9696356275303644
______________________________________________

Accuracy: 0.9686520376175548
[[896  52]
 [  8 958]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       948
           1       0.95      0.99      0.97       966

   micro avg       0.97      0.97      0.97      1914
   macro avg       0.97      0.97      0.97      1914
weighted avg       0.97      0.97      0.97      1914



In [25]:
    display_metrics("Random  Forest",random_forest_pred(X12_train,Y12_train,X12_test),Y12_test)

______________________________________________
Classifier: Random  Forest
Accuracy: 0.972391202620496
AUC: 0.9728429114341207
Precision: 0.9905392620624409
Recall: 0.9552919708029197
F1-score: 0.9725963771481654
______________________________________________

Accuracy: 0.972391202620496
[[1031   49]
 [  10 1047]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97      1080
           1       0.96      0.99      0.97      1057

   micro avg       0.97      0.97      0.97      2137
   macro avg       0.97      0.97      0.97      2137
weighted avg       0.97      0.97      0.97      2137



In [26]:
    display_metrics("Random  Forest",random_forest_pred(X18_train,Y18_train,X18_test),Y18_test)

______________________________________________
Classifier: Random  Forest
Accuracy: 0.9629629629629629
AUC: 0.9649351305812974
Precision: 0.9893805309734514
Recall: 0.9418702611625948
F1-score: 0.9650410012947778
______________________________________________

Accuracy: 0.9629629629629629
[[ 988   69]
 [  12 1118]]
              precision    recall  f1-score   support

           0       0.99      0.93      0.96      1057
           1       0.94      0.99      0.97      1130

   micro avg       0.96      0.96      0.96      2187
   macro avg       0.96      0.96      0.96      2187
weighted avg       0.96      0.96      0.96      2187



In [27]:
    display_metrics("Neural Network",neural_ntwrk_pred(X6_train,Y6_train,X6_test),Y6_test)

______________________________________________
Classifier: Neural Network
Accuracy: 0.9670846394984326
AUC: 0.9685205784204671
Precision: 0.9927536231884058
Recall: 0.9448275862068966
F1-score: 0.9681978798586572
______________________________________________

Accuracy: 0.9670846394984326
[[892  56]
 [  7 959]]
              precision    recall  f1-score   support

           0       0.99      0.94      0.97       948
           1       0.94      0.99      0.97       966

   micro avg       0.97      0.97      0.97      1914
   macro avg       0.97      0.97      0.97      1914
weighted avg       0.97      0.97      0.97      1914



In [28]:
  display_metrics("Neural Network",neural_ntwrk_pred(X12_train,Y12_train,X12_test),Y12_test)

______________________________________________
Classifier: Neural Network
Accuracy: 0.9747309312119794
AUC: 0.9753343748575356
Precision: 0.9952696310312205
Recall: 0.9554950045413261
F1-score: 0.9749768303985171
______________________________________________

Accuracy: 0.9747309312119794
[[1031   49]
 [   5 1052]]
              precision    recall  f1-score   support

           0       1.00      0.95      0.97      1080
           1       0.96      1.00      0.97      1057

   micro avg       0.97      0.97      0.97      2137
   macro avg       0.98      0.97      0.97      2137
weighted avg       0.98      0.97      0.97      2137



In [29]:
  display_metrics("Neural Network",neural_ntwrk_pred(X18_train,Y18_train,X18_test),Y18_test)

______________________________________________
Classifier: Neural Network
Accuracy: 0.9670781893004116
AUC: 0.967586122431175
Precision: 0.9787610619469026
Recall: 0.9584055459272097
F1-score: 0.968476357267951
______________________________________________

Accuracy: 0.9670781893004116
[[1009   48]
 [  24 1106]]
              precision    recall  f1-score   support

           0       0.98      0.95      0.97      1057
           1       0.96      0.98      0.97      1130

   micro avg       0.97      0.97      0.97      2187
   macro avg       0.97      0.97      0.97      2187
weighted avg       0.97      0.97      0.97      2187

